### ISSUE TITLE
xyz-java is not working

### ISSUE THREAD

**Issue by hamidmass** [bspk/oauth.xyz-java#2]
Hello sir, 
I’m trying to test the implementation of XYZ in Java to understand the transactional authorization protocol XYZ, but the implementation is not working. I have followed the steps described in the readme but I get the 500 Internal Server Error when I’m trying to click on one of the buttons (see attached screenshot). 
<img width="1017" alt="Capture d’écran 2020-04-20 à 12 35 00" src="https://user-images.githubusercontent.com/49214108/79750012-7e4e5680-8310-11ea-8463-6ed171d4aecb.png">
Any idea on what we need to do ? 
To facilitate our debug, is there any information or script on the structure of the mongoDB database ? ( because It would be easier during testing to host it within mongoDB Atlas).
Thank you in advance for you help.

**Comment by jricher** [comment]
I'd need to see more details of those errors, as it working as intended here. Are there any additional error messages from the Java console? Are you running the code as a Spring Boot app?

**Comment by hamidmass** [comment]
Hello sir, 
Thank you for your response. I do have additional error message besides the one that I showed you (see attached screenshot). 
<img width="1680" alt="Capture d’écran 2020-04-20 à 18 03 10" src="https://user-images.githubusercontent.com/49214108/79774638-5c1a0000-8333-11ea-9e5f-e6733ca0dea9.png">
I have followed precisely the steps described in the readme : 
	1. git clone 
	2. docker-compose up  
	3. mvn spring-boot: run 
I have the following versions of : 
 -> docker-compose version 1.25.4
 -> mvn 
<img width="823" alt="Capture d’écran 2020-04-20 à 18 19 30" src="https://user-images.githubusercontent.com/49214108/79774759-88358100-8333-11ea-9c70-b3bf997c22cc.png">
Thank you in advance for you help.

**Comment by fimbault** [comment]
Hi, 
I had the same issue. It's due to the docker configuration, set to work for windows. 

On linux: 
you need to change host.docker.internal to localhost in file oauth.xyz-java/src/main/resources/application.yml

And then http://localhost:9834/c should work. For spa I don't know, haven't tried.

**Comment by jricher** [comment]
Ah, that makes sense -- on our setup we have `host.docker.internal` set on the dev machines host file so that it's accessible the same way inside and outside the container.

```
127.0.0.1	localhost localunixsocket localunixsocket.local localunixsocket.home host.docker.internal
```

**Comment by hamidmass** [comment]
Everything works well. Thank you so much 👍
